name: Cypress Tests

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

  tests:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Run Automation tests
        run: npm run cy:run -- --browser firefox --env grepTags="@Envtest1",ENV="staging"
